name: Disabled Build Workflow

on: {}

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow is disabled
        run: echo "This build workflow is intentionally disabled." 