name: Disabled Docker Build Workflow

on: {}

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow is disabled
        run: echo "This Docker build workflow is intentionally disabled." 